# Generated by Django 2.1.1 on 2018-10-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaasApplication', '0003_auto_20181008_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_active',
            field=models.BooleanField(auto_created=True, default=True),
        ),
    ]
