# Generated by Django 2.1.1 on 2018-10-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaasApplication', '0004_auction_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='currentBid',
            field=models.IntegerField(auto_created=True, default=0),
        ),
    ]
