# Generated by Django 2.1.1 on 2018-10-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yaasApplication', '0007_auto_20181017_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='winner',
        ),
    ]
