# Generated by Django 2.1.1 on 2018-10-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaasApplication', '0010_auto_20181017_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='currentBid',
            field=models.DecimalField(auto_created=True, decimal_places=2, default=0, max_digits=6),
        ),
    ]
