# Generated by Django 2.1.1 on 2018-10-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaasApplication', '0013_auto_20181017_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='isBanned',
            field=models.BooleanField(default=False),
        ),
    ]
