# Generated by Django 2.1.1 on 2018-10-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaasApplication', '0014_auction_isbanned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='isBanned',
            field=models.BooleanField(auto_created=True, default=False),
        ),
    ]
