# Generated by Django 2.1.1 on 2018-10-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaasApplication', '0015_auto_20181017_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('de', 'German'), ('en', 'English'), ('sv', 'Swedish')], max_length=4, verbose_name='Interface Language')),
            ],
        ),
    ]
