# Generated by Django 2.1.1 on 2018-10-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('yaasApplication', '0017_auto_20181019_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='CustomerUser',
        ),
    ]
