# Generated by Django 2.1.1 on 2018-10-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaasApplication', '0018_auto_20181019_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='lockedby',
            field=models.TextField(default=''),
        ),
    ]
